import { useState } from 'react';
import { PDFViewer, Document, Page, Text, View, StyleSheet, pdf } from '@react-pdf/renderer';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { INITIAL_FORM_DATA } from '@/constants';

const styles = StyleSheet.create({
  page: { padding: 30 },
  section: { marginBottom: 10 },
});

function MyDocument({
  formData,
}: {
  formData: {
    companyName: string;
    companyAddress: string;
    companyPhoneNumber: string;
    clientCompanyName: string;
    clientAddress: string;
    clientPhoneNumber: string;
  };
}) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.section}>
          <Text>Company: {formData.companyName}</Text>
        </View>
        <View style={styles.section}>
          <Text>Address: {formData.companyAddress}</Text>
        </View>
        <View style={styles.section}>
          <Text>Phone: {formData.companyPhoneNumber}</Text>
        </View>
        <View style={styles.section}>
          <Text>Client: {formData.clientCompanyName}</Text>
        </View>
        <View style={styles.section}>
          <Text>Client Address: {formData.clientAddress}</Text>
        </View>
        <View style={styles.section}>
          <Text>Client Phone: {formData.clientPhoneNumber}</Text>
        </View>
      </Page>
    </Document>
  );
}

export default function Pdf1() {
  const [companyName, setCompanyName] = useState(INITIAL_FORM_DATA.companyName);
  const [companyAddress, setCompanyAddress] = useState(INITIAL_FORM_DATA.companyAddress);
  const [companyPhoneNumber, setCompanyPhoneNumber] = useState(
    INITIAL_FORM_DATA.companyPhoneNumber
  );
  const [clientCompanyName, setClientCompanyName] = useState(INITIAL_FORM_DATA.clientCompanyName);
  const [clientAddress, setClientAddress] = useState(INITIAL_FORM_DATA.clientAddress);
  const [clientPhoneNumber, setClientPhoneNumber] = useState(INITIAL_FORM_DATA.clientPhoneNumber);

  const formData = {
    companyName,
    companyAddress,
    companyPhoneNumber,
    clientCompanyName,
    clientAddress,
    clientPhoneNumber,
  };

  const downloadPDF = async () => {
    const blob = await pdf(<MyDocument formData={formData} />).toBlob();
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'generated_document.pdf';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div style={{ textAlign: 'left' }}>
      <h1 className="text-3xl font-medium mb-6">PDF Generation with @react-pdf</h1>
      <h3 style={{ fontWeight: 'bold', marginBottom: '20px' }}>
        pdf file generated by{'  '}
        <a
          href="https://www.npmjs.com/package/@react-pdf/renderer"
          target="_blank"
          rel="noopener noreferrer"
          className="text-blue-600 hover:text-blue-800"
        >
          <em>@react-pdf/renderer</em>
        </a>{' '}
        package
      </h3>
      <div style={{ marginBottom: '52px' }}>
        <div style={{ marginBottom: '15px' }}>
          <h4 style={{ marginBottom: '10px', fontWeight: 'bold' }}>Company Information</h4>
          <div style={{ display: 'flex', gap: '20px' }}>
            <div style={{ flex: 1 }}>
              <label>
                Company Name:
                <br />
                <Input
                  type="text"
                  value={companyName}
                  onChange={(e) => setCompanyName(e.target.value)}
                />
              </label>
            </div>
            <div style={{ flex: 1 }}>
              <label>
                Company Address:
                <br />
                <Input
                  type="text"
                  value={companyAddress}
                  onChange={(e) => setCompanyAddress(e.target.value)}
                />
              </label>
            </div>
            <div style={{ flex: 1 }}>
              <label>
                Company Phone Number:
                <br />
                <Input
                  type="tel"
                  value={companyPhoneNumber}
                  onChange={(e) => setCompanyPhoneNumber(e.target.value)}
                />
              </label>
            </div>
          </div>
        </div>
        <div style={{ marginTop: '24px' }}>
          <h4 style={{ marginBottom: '10px', fontWeight: 'bold' }}>Client Information</h4>
          <div style={{ display: 'flex', gap: '20px' }}>
            <div style={{ flex: 1 }}>
              <label>
                Client Company Name:
                <br />
                <Input
                  type="text"
                  value={clientCompanyName}
                  onChange={(e) => setClientCompanyName(e.target.value)}
                />
              </label>
            </div>
            <div style={{ flex: 1 }}>
              <label>
                Client Address:
                <br />
                <Input
                  type="text"
                  value={clientAddress}
                  onChange={(e) => setClientAddress(e.target.value)}
                />
              </label>
            </div>
            <div style={{ flex: 1 }}>
              <label>
                Client Phone Number:
                <br />
                <Input
                  type="tel"
                  value={clientPhoneNumber}
                  onChange={(e) => setClientPhoneNumber(e.target.value)}
                />
              </label>
            </div>
          </div>
        </div>
      </div>

      <div style={{ marginBottom: '24px', display: 'flex', gap: '10px' }}>
        <Button onClick={downloadPDF}>Download PDF</Button>
      </div>

      <div
        style={{
          border: '1px solid #ccc',
          padding: '20px',
          minHeight: '1000px',
        }}
      >
        <h2>Document Preview</h2>
        <PDFViewer width="100%" height="1000px">
          <MyDocument formData={formData} />
        </PDFViewer>
      </div>
    </div>
  );
}
