import { useState, useCallback, useRef } from 'react';
import { TemplateHandler } from 'easy-template-x';
import { renderAsync } from 'docx-preview';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import invoiceUrl from '@/assets/INVOICE.docx?url';
import { INITIAL_FORM_DATA } from '@/constants';

const Docx5 = () => {
  const [companyAddress, setCompanyAddress] = useState(INITIAL_FORM_DATA.companyAddress);
  const [companyPhoneNumber, setCompanyPhoneNumber] = useState(
    INITIAL_FORM_DATA.companyPhoneNumber
  );
  const [companyName, setCompanyName] = useState(INITIAL_FORM_DATA.companyName);
  const [clientCompanyName, setClientCompanyName] = useState(INITIAL_FORM_DATA.clientCompanyName);
  const [clientAddress, setClientAddress] = useState(INITIAL_FORM_DATA.clientAddress);
  const [clientPhoneNumber, setClientPhoneNumber] = useState(INITIAL_FORM_DATA.clientPhoneNumber);
  const [templateBuffer, setTemplateBuffer] = useState<ArrayBuffer | null>(null);
  const [generatedBuffer, setGeneratedBuffer] = useState<ArrayBuffer | null>(null);
  const previewRef = useRef<HTMLDivElement>(null);

  const generatePreview = useCallback(async () => {
    if (!templateBuffer) return;
    try {
      const data = {
        companyAddress,
        companyPhoneNumber,
        companyName,
        clientCompanyName,
        clientAddress,
        clientPhoneNumber,
      };

      // Create template handler
      const handler = new TemplateHandler();

      // Process the template with data
      const buffer = await handler.process(templateBuffer, data);

      setGeneratedBuffer(buffer);

      const blob = new Blob([buffer], {
        type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
      });

      // Clear and render preview
      if (previewRef.current) {
        previewRef.current.innerHTML = '';
        await renderAsync(blob, previewRef.current);

        // Add CSS to left-align content
        const style = document.createElement('style');
        style.textContent = `
          .docx-wrapper * { text-align: left !important; }
          .docx-wrapper table { margin: 0 auto; }
        `;
        previewRef.current.appendChild(style);
      }
    } catch (error) {
      console.error('Error generating document:', error);
      alert('Error generating document. Please check the inputs.');
    }
  }, [
    templateBuffer,
    companyAddress,
    companyPhoneNumber,
    companyName,
    clientCompanyName,
    clientAddress,
    clientPhoneNumber,
  ]);

  const handleFileUpload = async (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (file && file.name.endsWith('.docx')) {
      try {
        const arrayBuffer = await file.arrayBuffer();
        setTemplateBuffer(arrayBuffer);
        setGeneratedBuffer(null); // Reset generated buffer when new template is loaded
      } catch (error) {
        console.error('Error loading docx:', error);
        alert('Error loading the document. Please check the file.');
      }
    } else {
      alert('Please select a valid .docx file.');
    }
  };

  const downloadDocument = () => {
    if (!generatedBuffer) return;
    const blob = new Blob([generatedBuffer], {
      type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'filled_document.docx';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const downloadExample = () => {
    const link = document.createElement('a');
    link.href = invoiceUrl;
    link.download = 'INVOICE.docx';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div style={{ textAlign: 'left' }}>
      <h1 className="text-3xl font-medium mb-6">Templating for docx file with easy-template-x</h1>

      <h3 style={{ fontWeight: 'bold', marginBottom: '20px' }}>
        docx file generated by{'  '}
        <a
          href="https://www.npmjs.com/package/easy-template-x"
          target="_blank"
          rel="noopener noreferrer"
          className="text-blue-600 hover:text-blue-800"
        >
          <em>easy-template-x</em>
        </a>{' '}
        package
      </h3>

      <p style={{ marginBottom: '20px' }}>
        Template variables use <b>{`{variableName}`}</b> syntax and are replaced with
        corresponding values from your JSON data.
      </p>

      <div style={{ marginBottom: '52px' }}>
        <div style={{ marginBottom: '16px' }}>
          <h4 style={{ marginBottom: '10px', fontWeight: 'bold' }}>Company Information</h4>
          <div style={{ display: 'flex', gap: '20px' }}>
            <div style={{ flex: 1 }}>
              <label>
                Company Name:
                <Input
                  type="text"
                  value={companyName}
                  onChange={(e) => setCompanyName(e.target.value)}
                />
              </label>
            </div>
            <div style={{ flex: 1 }}>
              <label>
                Company Address:
                <Input
                  type="text"
                  value={companyAddress}
                  onChange={(e) => setCompanyAddress(e.target.value)}
                />
              </label>
            </div>
            <div style={{ flex: 1 }}>
              <label>
                Company Phone Number:
                <Input
                  type="tel"
                  value={companyPhoneNumber}
                  onChange={(e) => setCompanyPhoneNumber(e.target.value)}
                />
              </label>
            </div>
          </div>
        </div>
        <div style={{ marginTop: '24px' }}>
          <h4 style={{ marginBottom: '10px', fontWeight: 'bold' }}>Client Information</h4>
          <div style={{ display: 'flex', gap: '20px' }}>
            <div style={{ flex: 1 }}>
              <label>
                Client Company Name:
                <Input
                  type="text"
                  value={clientCompanyName}
                  onChange={(e) => setClientCompanyName(e.target.value)}
                />
              </label>
            </div>
            <div style={{ flex: 1 }}>
              <label>
                Client Address:
                <Input
                  type="text"
                  value={clientAddress}
                  onChange={(e) => setClientAddress(e.target.value)}
                />
              </label>
            </div>
            <div style={{ flex: 1 }}>
              <label>
                Client Phone Number:
                <Input
                  type="tel"
                  value={clientPhoneNumber}
                  onChange={(e) => setClientPhoneNumber(e.target.value)}
                />
              </label>
            </div>
          </div>
        </div>
      </div>

      <p style={{ marginBottom: '20px' }}>
        <Button onClick={downloadExample} variant="outline">
          Download example DOCX template with variables
        </Button>
      </p>

      <input
        type="file"
        accept=".docx"
        onChange={handleFileUpload}
        style={{ display: 'none' }}
        id="docx-upload"
      />
      <div
        style={{ marginBottom: '24px', display: 'flex', gap: '12px', justifyContent: 'flex-start' }}
      >
        <Button onClick={() => document.getElementById('docx-upload')?.click()} variant="outline">
          Choose DOCX File
        </Button>
        <Button onClick={generatePreview} disabled={!templateBuffer}>
          Generate Document
        </Button>
        <Button onClick={downloadDocument} disabled={!generatedBuffer}>
          Download Filled Document
        </Button>
      </div>

      <h3 style={{ fontWeight: 'bold', marginBottom: '24px' }}>
        Preview by{' '}
        <a
          href="https://www.npmjs.com/package/docx-preview"
          target="_blank"
          rel="noopener noreferrer"
          className="text-blue-600 hover:text-blue-800"
        >
          <em>docx-preview</em>
        </a>{' '}
        package
      </h3>

      <div
        ref={previewRef}
        style={{
          border: '1px solid #ccc',
          padding: '20px',
          minHeight: '500px',
        }}
      />
    </div>
  );
};

export default Docx5;
